### ISSUE TITLE
PluginTagTypeTest unit test causes System.Exception in ubuntu

### ISSUE THREAD

**Issue by jrshoare** [jrshoare/lcmsNET#3]
When running unit tests via github actions in 'ubuntu-latest' the test 'PluginTagTypeTest' causes the following exception:

Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)

This error does not occur when running the same unit test in Windows.

**Comment by jrshoare** [comment]
Fixed in commit revision 345fe0906b1fd05693f12a37cd7484db0f23beed
